# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 374af45ce30ba6ef5ef2bd206cfcca6b077e8be110ced781c2bf0cad8da16295d870d08574bd232b86ed4189e3a314c56cb671964a9f6d1f6b7c9338461caeea

test:
  secret_key_base: 7f91d4e4e23ebcb9bffda17b098b388f88f57db12b0efef5a0c8feb302a52d383ecc74a94acb6deda844640908ff671c20220d72d955a727c2bd3ad0cc2f518e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
